# Generated by Django 5.1 on 2025-09-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xocolatl_catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('chocolates', 'Chocolates'), ('crepas', 'Crepas'), ('alimentos', 'Alimentos')], default='chocolates', max_length=20),
        ),
    ]
